version: '3.8'

services:
  backend:
    build:
      context: ./pass_vault
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - FASTAPI_ENV=development
    volumes:
      - ./pass_vault:/app
      - backend_data:/app/data
    networks:
      - app-network
    restart: unless-stopped
    command: ["python", "main.py", "--mode", "server", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    command: ["npm", "run", "dev"]

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge 